In [97]:
## JSON exercise

#Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
#1. Find the 10 countries with most projects
#2. Find the top 10 major project themes (using column 'mjtheme_namecode')
#3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [98]:
import numpy as np
import pandas as pd
import json
from pandas.io.json import json_normalize

In [99]:
#read in data 
projects_df=pd.read_json('data/world_bank_projects.json')
#get an idea of your data
pd.set_option('display.max_colwidth', -1)
projects_df.head(20)

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Percent': 30, 'Name': 'Other economic management'}","[{'code': '24', 'name': 'Other economic management'}, {'code': '54', 'name': 'Social safety nets'}]","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{'$oid': '52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,TI,IBRD,Active,Y,"{'Percent': 46, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'}, {'code': '25', 'name': 'Administrative and civil service reform'}, {'code': '81', 'name': 'Climate change'}, {'code': '52', 'name': 'Natural disaster management'}]","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{'$oid': '52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of",...,JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Participation and civic engagement'}","[{'code': '57', 'name': 'Participation and civic engagement'}, {'code': '59', 'name': 'Gender'}]","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{'$oid': '52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,...,"FH,YW,YZ",IBRD,Active,N,"{'Percent': 30, 'Name': 'Export development and competitiveness'}","[{'code': '45', 'name': 'Export development and competitiveness'}, {'code': '41', 'name': 'Micro, Small and Medium Enterprise support'}]","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/second-private-sector-competitiveness-economic-diversification?lang=en
5,{'$oid': '52b213b38594d8a2be17c785'},2014,October,2013-10-31T00:00:00Z,REPUBLIC OF KENYA,NaN,Republic of Kenya!$!KE,KE,Republic of Kenya,Kenya,...,JB,IBRD,Active,Y,"{'Percent': 100, 'Name': 'Social safety nets'}","[{'code': '54', 'name': 'Social safety nets'}]",54,10000000,10000000,http://www.worldbank.org/projects/P146161?lang=en
6,{'$oid': '52b213b38594d8a2be17c786'},2014,October,2013-10-29T00:00:00Z,GOVERNMENT OF INDIA,2019-06-30T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,TI,IBRD,Active,N,"{'Percent': 20, 'Name': 'Administrative and civil service reform'}","[{'code': '25', 'name': 'Administrative and civil service reform'}, {'code': '39', 'name': 'Infrastructure services for private sector development'}]","39,25",500000000,500000000,http://www.worldbank.org/projects/P121185/first-national-highways-interconnectivity-improvement-project?lang=en
7,{'$oid': '52b213b38594d8a2be17c787'},2014,October,2013-10-29T00:00:00Z,PEOPLE'S REPUBLIC OF CHINA,NaN,People's Republic of China!$!CN,CN,People's Republic of China,China,...,LR,IBRD,Active,N,"{'Percent': 100, 'Name': 'Climate change'}","[{'code': '81', 'name': 'Climate change'}]",81,0,27280000,http://www.worldbank.org/projects/P127033/china-renewable-energy-scale-up-program-phase-ii?lang=en
8,{'$oid': '52b213b38594d8a2be17c788'},2014,October,2013-10-29T00:00:00Z,THE GOVERNMENT OF INDIA,2018-12-31T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,TI,IBRD,Active,N,"{'Percent': 87, 'Name': 'Other rural development'}","[{'code': '79', 'name': 'Other rural development'}]",79,160000000,160000000,http://www.worldbank.org/projects/P130164/rajasthan-road-sector-modernization-project?lang=en
9,{'$oid': '52b213b38594d8a2be17c789'},2014,October,2013-10-29T00:00:00Z,THE KINGDOM OF MOROCCO,2014-12-31T00:00:00Z,Kingdom of Morocco!$!MA,MA,Kingdom of Morocco,Morocco,...,"BM,BC,BZ",IBRD,Active,N,"{'Percent': 33, 'Name': 'Other accountability/anti-corruption'}","[{'code': '29', 'name': 'Other accountability/anti-corruption'}, {'code': '30', 'name': 'Other public sector governance'}, {'code': '27', 'name': 'Public expenditure, financial management and procurement'}]","27,30,29",200000000,200000000,http://www.worldbank.org/projects/P130903?lang=en
10,{'$oid': '52b213b38594d8a2be17c78a'},2014,October,2013-10-25T00:00:00Z,GOVERNMENT OF SOUTH SUDAN,NaN,Republic of South Sudan!$!SS,SS,Republic of South Sudan,South Sudan,...,"AZ,JB,AH",IBRD,Active,Y,"{'Percent': 100, 'Name': 'Global food crisis response'}","[{'code': '91', 'name': 'Global food crisis response'}]",91,0,7530000,http://www.worldbank.org/projects/P145339?lang=en
11,{'$oid': '52b213b38594d8a2be17c78b'},2014,October,2013-10-25T00:00:00Z,NaN,2017-12-31T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,"JB,YC,WD,TI",IBRD,Active,N,"{'Percent': 60, 'Name': 'Rural services and infrastructure'}","[{'code': '78', 'name': 'Rural services and infrastructure'}, {'code': '52', 'name': 'Natural disaster management'}, {'code': '87', 'name': 'Social risk mitigation'}, {'code': '81', 'name': 'Climate change'}]","81,87,52,78",250000000,250000000,http://www.worldbank.org/projects/P146653?lang=en
12,{'$oid': '52b213b38594d8a2be17c78c'},2014,October,2013-10-24T00:00:00Z,GOVERNMENT OF GHANA,2019-06-30T00:00:00Z,Republic of Ghana!$!GH,GH,Republic of Ghana,Ghana,...,CZ,IBRD,Active,N,"{'Percent': 0, 'Name': ''}",NaN,NaN,97000000,97000000,http://www.worldbank.org/projects/P144140/gh-etransform-ghana?lang=en
13,{'$oid': '52b213b38594d8a2be17c78d'},2014,October,2013-10-22T00:00:00Z,GOVERNMENT OF TIMOR LESTE,NaN,Democratic Republic of Timor-Leste!$!TP,TP,Democratic Republic of Timor-Leste,Timor-Leste,...,"BV,TI",IBRD,Active,Y,"{'Percent': 20, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'}, {'code': '81', 'name': 'Climate change'}, {'code': '78', 'name': 'Rural services and infrastructure'}]","78,81,47",40000000,40000000,http://www.worldbank.org/projects/P130975/timor-leste-road-climate-resilience-project-additional-financing?lang=en
14,{'$oid': '52b213b38594d8a2be17c78e'},2014,October,2013-10-22T00:00:00Z,GOVERNMENT OF JORDAN,NaN,Hashemite Kingdom of Jordan!$!JO,JO,Hashemite Kingdom of Jordan,Jordan,...,JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Social safety nets'}","[{'code': '54', 'name': 'Social safety nets'}, {'code': '56', 'name': 'Other social protection and risk management'}, {'code': '53', 'name': 'Poverty strategy, analysis and monitoring'}]","53,56,54",0,9500000,http://www.worldbank.org/projects/P144832?lang=en
15,{'$oid': '52b213b38594d8a2be17c78f'},2014,October,2013-10-17T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Samoa!$!WS,WS,Samoa,Samoa,...,TI,IBRD,Active,N,"{'Percent': 60, 'Name': 'Rural services and infrastructure'}","[{'code': '78', 'name': 'Rural services and infrastructure'}, {'code': '81', 'name': 'Climate change'}, {'code': '49', 'name': 'Trade facilitation and market access'}]","49,81,78",20000000,20000000,http://www.worldbank.org/projects/P145545?lang=en
16,{'$oid': '52b213b38594d8a2be17c790'},2014,October,2013-10-17T00:00:00Z,MINISTRY OF FINANCE,2015-12-31T00:00:00Z,Samoa!$!WS,WS,Samoa,Samoa,...,"AZ,AJ,AH",IBRD,Active,N,"{'Percent': 100, 'Name': 'Other rural development'}","[{'code': '79', 'name': 'Other rural development'}]",79,5000000,5000000,http://www.worldbank.org/projects/P145938?lang=en
17,{'$oid': '52b213b38594d8a2be17c791'},2014,October,2013-10-16T00:00:00Z,MINISTRY OF FINANCE AND BUDGET (MFB),NaN,Republic of Madagascar!$!MG,MG,Republic of Madagascar,Madagascar,...,EP,IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,0,85400000,http://www.worldbank.org/projects/P132616?lang=en
18,{'$oid': '52b213b38594d8a2be17c792'},2014,October,2013-10-16T00:00:00Z,ROYAL GOVERNMENT OF CAMBODIA,NaN,Kingdom of Cambodia!$!KH,KH,Kingdom of Cambodia,Cambodia,...,"BK,JB,BH,BC,JA",IBRD,Active,Y,"{'Percent': 17, 'Name': 'Child health'}","[{'code': '63', 'name': 'Child health'}, {'code': '67', 'name': 'Health system performance'}, {'code': '25', 'name': 'Administrative and civil service reform'}, {'code': '57', 'name': 'Participation and civic engagement'}, {'code': '69', 'name': 'Population and reproductive health'}]","69,57,25,67,63",0,13450000,http://www.worldbank.org/projects/P146271?lang=en
19,{'$oid': '52b213b38594d8a2be17c793'},2014,October,2013-10-10T00:00:00Z,MINISTRY OF FINANCE,NaN,Kingdom of Morocco!$!MA,MA,Kingdom of Morocco,Morocco,...,"BH,BC,BZ",IBRD,Active,N,"{'Percent': 40, 'Name': 'Public expenditure, financial management and procurement'}","[{'code': '27', 'name': 'Public expenditure, financial management and procurement'}, {'code': '26', 'name': 'Decentralization'}, {'code': '25', 'name': 'Administrative and civil service reform'}]","25,26,27",0,4350000,http://www.worldbank.org/projects/P143979?lang=en

In [102]:
#view the full row to understand better
pd.set_option('display.max_colwidth', -1)
projects_df.mjtheme_namecode.head(10)

0    [{'code': '8', 'name': 'Human development'}, {'code': '11', 'name': ''}]
1    [{'code': '1', 'name': 'Economic management'}, {'code': '6', 'name': 'Social protection and risk management'}]
2    [{'code': '5', 'name': 'Trade and integration'}, {'code': '2', 'name': 'Public sector governance'}, {'code': '11', 'name': 'Environment and natural resources management'}, {'code': '6', 'name': 'Social protection and risk management'}]
3    [{'code': '7', 'name': 'Social dev/gender/inclusion'}, {'code': '7', 'name': 'Social dev/gender/inclusion'}]
4    [{'code': '5', 'name': 'Trade and integration'}, {'code': '4', 'name': 'Financial and private sector development'}]
5    [{'code': '6', 'name': 'Social protection and risk management'}, {'code': '6', 'name': ''}]
6    [{'code': '2', 'name': 'Public sector governance'}, {'code': '4', 'name': 'Financial and private sector development'}]
7    [{'code': '11', 'name': 'Environment and natural resources management'}, {'code': '8', 'name': ''}]
8    [{'code': '10', 'name': 'Rural development'}, {'code': '7', 'name': ''}]
9    [{'code': '2', 'name': 'Public sector governance'}, {'code': '2', 'name': 'Public sector governance'}, {'code': '2', 'name': 'Public sector governance'}]
Name: mjtheme_namecode, dtype: object

In [103]:
#1. Find the 10 countries with most projects
projects_df.groupby('countryname').size().sort_values(ascending=False).head(10)

countryname
People's Republic of China         19
Republic of Indonesia              19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
Nepal                              12
People's Republic of Bangladesh    12
Kingdom of Morocco                 12
Africa                             11
Republic of Mozambique             11
dtype: int64

In [104]:
#2. Find the top 10 major project themes (using column 'mjtheme_namecode')
# load in data and use json_normalize to create tables from nested element using the id as an index (unique for each row)
data=json.load((open('data/world_bank_projects.json')))
mjtheme_namecode=json_normalize(data,'mjtheme_namecode',['id'])

In [105]:
mjtheme_namecode.head()

  code                                   name       id
0  8    Human development                      P129828
1  11                                          P129828
2  1    Economic management                    P144674
3  6    Social protection and risk management  P144674
4  5    Trade and integration                  P145310

In [109]:
mjtheme_blanks = mjtheme_namecode[(mjtheme_namecode.name =="" )]
mjtheme_blanks.groupby('id').size().sort_values(ascending = False)
#note that there are no duplicate ids in the data set

id
P146161    1
P127143    1
P127201    1
P127306    1
P127388    1
P127435    1
P127966    1
P128282    1
P128289    1
P128309    1
P128966    1
P129177    1
P129206    1
P129220    1
P129332    1
P129397    1
P129431    1
P129704    1
P129828    1
P129929    1
P130164    1
P130412    1
P130461    1
P130786    1
P130864    1
P131049    1
P131094    1
P131202    1
P131204    1
P127144    1
          ..
P143324    1
P143192    1
P132807    1
P131631    1
P131640    1
P131777    1
P131881    1
P132108    1
P132116    1
P132138    1
P132154    1
P132541    1
P132616    1
P132679    1
P132798    1
P132831    1
P133831    1
P132881    1
P132920    1
P133005    1
P133184    1
P133191    1
P133230    1
P133434    1
P133442    1
P133471    1
P133554    1
P133557    1
P133729    1
P098847    1
Length: 122, dtype: int64

In [110]:
#here are my top 10 themes in descending order, head(11) is used because a large number of rows have a blank "name"
mjtheme_namecode.groupby('name').size().sort_values(ascending = False).head(11)

name
Environment and natural resources management    223
Rural development                               202
Human development                               197
Public sector governance                        184
Social protection and risk management           158
Financial and private sector development        130
                                                122
Social dev/gender/inclusion                     119
Trade and integration                           72
Urban development                               47
Economic management                             33
dtype: int64

In [111]:
#3. In 2. above you will notice that some entries have only the code and the name is missing. 
#Create a dataframe with the missing names filled in.

In [112]:
#double check that every id possible has a theme name somewhere (so you can create a lookup from this dataframe)
themelkup = mjtheme_namecode[['code','name']]
themelkup.groupby(['code', 'name']).size()

code  name
1                                                     5
      Economic management                             33
10                                                    14
      Rural development                               202
11                                                    27
      Environment and natural resources management    223
2                                                     15
      Public sector governance                        184
3                                                     3
      Rule of law                                     12
4                                                     16
      Financial and private sector development        130
5                                                     5
      Trade and integration                           72
6                                                     10
      Social protection and risk management           158
7                                                     11
      Social dev/gender/inclusion                     119
8                                                     13
      Human development                               197
9                                                     3
      Urban development                               47
dtype: int64

In [113]:
#drop blanks
themelkup2 = themelkup[themelkup['name'] != ""]
themelkup2

     code                                          name
0     8    Human development
2     1    Economic management
3     6    Social protection and risk management
4     5    Trade and integration
5     2    Public sector governance
6     11   Environment and natural resources management
7     6    Social protection and risk management
8     7    Social dev/gender/inclusion
9     7    Social dev/gender/inclusion
10    5    Trade and integration
11    4    Financial and private sector development
12    6    Social protection and risk management
14    2    Public sector governance
15    4    Financial and private sector development
16    11   Environment and natural resources management
18    10   Rural development
20    2    Public sector governance
21    2    Public sector governance
22    2    Public sector governance
23    10   Rural development
25    10   Rural development
26    6    Social protection and risk management
27    6    Social protection and risk management
28    11   Environment and natural resources management
30    5    Trade and integration
31    11   Environment and natural resources management
32    10   Rural development
33    6    Social protection and risk management
34    6    Social protection and risk management
35    6    Social protection and risk management
...  ..                                      ...
1465  11   Environment and natural resources management
1466  8    Human development
1467  2    Public sector governance
1468  2    Public sector governance
1469  8    Human development
1470  9    Urban development
1471  6    Social protection and risk management
1472  6    Social protection and risk management
1473  9    Urban development
1474  2    Public sector governance
1475  2    Public sector governance
1476  10   Rural development
1478  8    Human development
1479  7    Social dev/gender/inclusion
1480  11   Environment and natural resources management
1482  6    Social protection and risk management
1484  4    Financial and private sector development
1485  7    Social dev/gender/inclusion
1486  8    Human development
1487  5    Trade and integration
1488  2    Public sector governance
1489  8    Human development
1490  10   Rural development
1492  10   Rural development
1493  10   Rural development
1494  10   Rural development
1495  9    Urban development
1496  8    Human development
1497  5    Trade and integration
1498  4    Financial and private sector development

[1377 rows x 2 columns]

In [114]:
#create a lookup table of theme id by name
themelkup3 = themelkup2.drop_duplicates()
themelkup3.set_index('code').sort_index()

                                              name
code
1     Economic management
10    Rural development
11    Environment and natural resources management
2     Public sector governance
3     Rule of law
4     Financial and private sector development
5     Trade and integration
6     Social protection and risk management
7     Social dev/gender/inclusion
8     Human development
9     Urban development

In [115]:
#merge lookup table onto old dataframe to fill in theme name
mjtheme_namecode2 = pd.merge(mjtheme_namecode, themelkup3, on='code' )
#result = pd.merge(left, right, on='key')
mjtheme_namecode2

     code             name_x       id             name_y
0     8    Human development  P129828  Human development
1     8                       P127033  Human development
2     8    Human development  P132616  Human development
3     8    Human development  P146271  Human development
4     8    Human development  P146271  Human development
5     8    Human development  P146271  Human development
6     8    Human development  P146109  Human development
7     8    Human development  P146109  Human development
8     8    Human development  P143025  Human development
9     8    Human development  P122700  Human development
10    8    Human development  P145118  Human development
11    8    Human development  P128628  Human development
12    8                       P098847  Human development
13    8    Human development  P125018  Human development
14    8    Human development  P132753  Human development
15    8    Human development  P132753  Human development
16    8    Human development  P132753  Human development
17    8    Human development  P131202  Human development
18    8    Human development  P126130  Human development
19    8    Human development  P126130  Human development
20    8    Human development  P126130  Human development
21    8    Human development  P126034  Human development
22    8    Human development  P131212  Human development
23    8    Human development  P131441  Human development
24    8    Human development  P144532  Human development
25    8    Human development  P144532  Human development
26    8    Human development  P123503  Human development
27    8                       P123503  Human development
28    8    Human development  P120397  Human development
29    8    Human development  P143060  Human development
...  ..                  ...      ...                ...
1469  9    Urban development  P130972  Urban development
1470  9    Urban development  P130972  Urban development
1471  9    Urban development  P130972  Urban development
1472  9    Urban development  P101289  Urban development
1473  9    Urban development  P118152  Urban development
1474  9    Urban development  P130528  Urban development
1475  9    Urban development  P130461  Urban development
1476  9    Urban development  P130174  Urban development
1477  9    Urban development  P131394  Urban development
1478  9    Urban development  P112901  Urban development
1479  9    Urban development  P112901  Urban development
1480  9    Urban development  P118916  Urban development
1481  9    Urban development  P128763  Urban development
1482  9    Urban development  P128763  Urban development
1483  9    Urban development  P126321  Urban development
1484  3    Rule of law        P128443  Rule of law
1485  3    Rule of law        P130459  Rule of law
1486  3    Rule of law        P127787  Rule of law
1487  3                       P131640  Rule of law
1488  3    Rule of law        P144386  Rule of law
1489  3    Rule of law        P144386  Rule of law
1490  3                       P145095  Rule of law
1491  3    Rule of law        P121152  Rule of law
1492  3                       P129332  Rule of law
1493  3    Rule of law        P105269  Rule of law
1494  3    Rule of law        P128950  Rule of law
1495  3    Rule of law        P130528  Rule of law
1496  3    Rule of law        P131767  Rule of law
1497  3    Rule of law        P125202  Rule of law
1498  3    Rule of law        P131266  Rule of law

[1499 rows x 4 columns]

In [117]:
#clean up final dataframe, here are all my project id's with the name of the theme filled in
mjtheme_final = mjtheme_namecode2[['code','id', 'name_y']]
mjtheme_final

     code       id             name_y
0     8    P129828  Human development
1     8    P127033  Human development
2     8    P132616  Human development
3     8    P146271  Human development
4     8    P146271  Human development
5     8    P146271  Human development
6     8    P146109  Human development
7     8    P146109  Human development
8     8    P143025  Human development
9     8    P122700  Human development
10    8    P145118  Human development
11    8    P128628  Human development
12    8    P098847  Human development
13    8    P125018  Human development
14    8    P132753  Human development
15    8    P132753  Human development
16    8    P132753  Human development
17    8    P131202  Human development
18    8    P126130  Human development
19    8    P126130  Human development
20    8    P126130  Human development
21    8    P126034  Human development
22    8    P131212  Human development
23    8    P131441  Human development
24    8    P144532  Human development
25    8    P144532  Human development
26    8    P123503  Human development
27    8    P123503  Human development
28    8    P120397  Human development
29    8    P143060  Human development
...  ..        ...                ...
1469  9    P130972  Urban development
1470  9    P130972  Urban development
1471  9    P130972  Urban development
1472  9    P101289  Urban development
1473  9    P118152  Urban development
1474  9    P130528  Urban development
1475  9    P130461  Urban development
1476  9    P130174  Urban development
1477  9    P131394  Urban development
1478  9    P112901  Urban development
1479  9    P112901  Urban development
1480  9    P118916  Urban development
1481  9    P128763  Urban development
1482  9    P128763  Urban development
1483  9    P126321  Urban development
1484  3    P128443  Rule of law
1485  3    P130459  Rule of law
1486  3    P127787  Rule of law
1487  3    P131640  Rule of law
1488  3    P144386  Rule of law
1489  3    P144386  Rule of law
1490  3    P145095  Rule of law
1491  3    P121152  Rule of law
1492  3    P129332  Rule of law
1493  3    P105269  Rule of law
1494  3    P128950  Rule of law
1495  3    P130528  Rule of law
1496  3    P131767  Rule of law
1497  3    P125202  Rule of law
1498  3    P131266  Rule of law

[1499 rows x 3 columns]